
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            "detections_json",
            default_value="/home/sunrise/rdk_normal_yolo_test/result/digua_oiv7_offline_detections.json",
            description="Offline detections JSON generated by offline_yolov8_oiv7_postprocess.py",
        ),
        DeclareLaunchArgument(
            "publish_rate",
            default_value="1.0",
            description="Publish rate for offline detections.",
        ),
        DeclareLaunchArgument(
            "image_width",
            default_value="640.0",
            description="Target camera image width.",
        ),
        DeclareLaunchArgument(
            "image_height",
            default_value="480.0",
            description="Target camera image height.",
        ),
        Node(
            package="digua_bpu_yolo",
            executable="offline_detections_publisher_node",
            name="offline_detections_publisher_node",
            output="screen",
            parameters=[{
                "detections_json": LaunchConfiguration("detections_json"),
                "publish_rate": LaunchConfiguration("publish_rate"),
                "image_width": LaunchConfiguration("image_width"),
                "image_height": LaunchConfiguration("image_height"),
                "model_width": 640.0,
                "model_height": 640.0,
                "frame_id": "camera_color_optical_frame",
                "topic": "/semantic/detections_json",
                "min_confidence": 0.0,
                "lowercase_label": True,
            }],
        ),
    ])
